version: 2

models:
  - name: classroom_surveys_merged
    description: "Deduped model"
    schema: production
    columns:
      - name: _airbyte_raw_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
        type: string

  - name: classroom_surveys_normalized
    description: "merged and score normalized"
    schema: production
    columns:
      - name: '"KEY"'
        description: "The primary key for this table"
        tests:
          - not_null
        type: string
