version: 2
models:
  - name: int_classroom_surveys_delhi
    description: Add survey form data
    +schema: intermediate
    columns:
      - name: '"KEY"'
        description: The primary key for this table
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: string
        type: string
      - name: submissiondate
        description: "Submission date"
        tests:
          - not_null
          - is_timestamp
      - name: region
        description: "Geographical region"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

  - name: int_classroom_surveys_ethiopia
    description: Add survey form data
    +schema: intermediate
    columns:
      - name: '"KEY"'
        description: The primary key for this table
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: string
      - name: submissiondate
        description: "Submission date"
        tests:
          - not_null
          - is_timestamp

  - name: int_classroom_surveys_tamil_nadu
    description: Add survey form data
    +schema: intermediate
    columns:
      - name: '"KEY"'
        description: The primary key for this table
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: submissiondate
        description: "Submission date"
        tests:
          - not_null
          - is_timestamp
      - name: region
        description: Region
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

  - name: int_classroom_surveys_karnataka
    description: Add survey form data
    +schema: intermediate
    columns:
      - name: '"KEY"'
        description: The primary key for this table
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: submissiondate
        description: "Submission date"
        tests:
          - not_null
          - is_timestamp
      - name: region
        description: "Submission date"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

  - name: int_classroom_surveys_indonesia
    description: Add survey form data
    +schema: intermediate
    columns:
      - name: '"KEY"'
        description: The primary key for this table
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: submissiondate
        description: "Submission date"
        tests:
          - not_null
          - is_timestamp
      - name: region
        description: "Submission date"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

  - name: int_classroom_surveys_uganda
    description: Add survey form data
    +schema: intermediate
    columns:
      - name: '"KEY"'
        description: The primary key for this table
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: string
      - name: submissiondate
        description: "Submission date"
        tests:
          - not_null
          - is_timestamp
