version: 2

models:
  - name: dev_classroom_surveys_delhi
    description: "Add survey form data"
    +schema: dev_intermediate
    columns:
      - name: '"KEY"'
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
        type: string

  - name: dev_classroom_surveys_tamil_nadu
    description: "Add survey form data"
    +schema: dev_intermediate
    columns:
      - name: '"KEY"'
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
        type: string

  - name: dev_classroom_surveys_karnataka
    description: "Add survey form data"
    +schema: dev_intermediate
    columns:
      - name: '"KEY"'
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
        type: string

  - name: dev_classroom_surveys_indonesia
    description: "Add survey form data"
    +schema: dev_intermediate
    columns:
      - name: '"KEY"'
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
        type: string

  - name: dev_classroom_surveys_uganda
    description: "Add survey form data"
    +schema: dev_intermediate
    columns:
      - name: '"KEY"'
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
        type: string

  - name: dev_classroom_surveys_ethiopia
    description: "Add survey form data"
    +schema: dev_intermediate
    columns:
      - name: '"KEY"'
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
        type: string
